// @aibos/docs-registry — Document Generation
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
// AUTHORITY: SRS-DOCSREG-001 §3.3, ADR-DOCSREG-001 ADR-004
// PURPOSE: Generate managed header blocks and INDEX.md
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

import Handlebars from "handlebars";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import type { DocsRegistryConfig, GenerateResult } from "../types/index.js";
import { computeChecksum } from "./checksum.js";
import { discoverDocs } from "./discovery.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const BEGIN_MARKER = "<!-- BEGIN: AIBOS_MANAGED -->";
const END_MARKER = "<!-- END: AIBOS_MANAGED -->";

/**
 * Load Handlebars template from custom or default location.
 */
function loadTemplate(
  templatesDir: string | undefined,
  name: string
): HandlebarsTemplateDelegate {
  const defaultPath = path.join(__dirname, "..", "templates", name);
  const customPath = templatesDir ? path.join(templatesDir, name) : null;

  const templatePath =
    customPath && fs.existsSync(customPath) ? customPath : defaultPath;

  if (!fs.existsSync(templatePath)) {
    throw new Error(`Template not found: ${templatePath}`);
  }

  const source = fs.readFileSync(templatePath, "utf8");
  return Handlebars.compile(source, { noEscape: true });
}

/**
 * Upsert managed block in markdown content.
 *
 * If markers exist, replaces content between them.
 * If no markers, prepends the managed block.
 */
function upsertManagedBlock(content: string, managed: string): string {
  const start = content.indexOf(BEGIN_MARKER);
  const end = content.indexOf(END_MARKER);

  if (start !== -1 && end !== -1 && end > start) {
    // Replace existing block
    return (
      content.slice(0, start) + managed + content.slice(end + END_MARKER.length)
    );
  }

  // No block exists — prepend
  return managed + "\n\n" + content.trimStart();
}

/**
 * Generate docs — update managed blocks and checksums.
 *
 * For each doc.json:
 * 1. Render managed header block from template
 * 2. Upsert block in doc.md
 * 3. Compute checksum
 * 4. Write checksum back to doc.json
 */
export async function generateDocs(
  config: DocsRegistryConfig
): Promise<GenerateResult> {
  const docs = await discoverDocs(config.docsDir);
  const headerTemplate = loadTemplate(config.templatesDir, "header.md.hbs");

  const result: GenerateResult = {
    processed: docs.length,
    updated: [],
    errors: [],
  };

  for (const doc of docs) {
    try {
      // Render managed block
      const managed = headerTemplate(doc.docJson);

      // Read existing doc.md or create empty
      const existingMd = fs.existsSync(doc.docMdPath)
        ? fs.readFileSync(doc.docMdPath, "utf8")
        : "";

      // Upsert managed block
      const newMd = upsertManagedBlock(existingMd, managed);

      // Write doc.md
      fs.writeFileSync(doc.docMdPath, newMd, "utf8");

      // Compute checksum
      const checksum = computeChecksum(newMd, config.checksumAlgorithm);

      // Update doc.json with checksum
      const updatedJson = { ...doc.docJson, checksum_sha256: checksum };
      fs.writeFileSync(
        doc.docJsonPath,
        JSON.stringify(updatedJson, null, 2) + "\n",
        "utf8"
      );

      result.updated.push(doc.docId);
    } catch (error) {
      result.errors.push({
        docId: doc.docId,
        error: error instanceof Error ? error.message : String(error),
      });
    }
  }

  return result;
}

/**
 * Generate INDEX.md from all discovered docs.
 *
 * INDEX is deterministic: same input always produces identical output.
 */
export async function generateIndex(config: DocsRegistryConfig): Promise<void> {
  const docs = await discoverDocs(config.docsDir);

  const rows = docs.map((doc) => {
    const relPath = path
      .relative(config.docsDir, doc.docMdPath)
      .replace(/\\/g, "/");
    const checksum = doc.docJson.checksum_sha256
      ? `\`${doc.docJson.checksum_sha256.slice(0, 16)}...\``
      : "`—`";

    return `| ${doc.docJson.document_id} | ${doc.docJson.title} | v${doc.docJson.version} | ${doc.docJson.status} | ${doc.docJson.authority} | ${checksum} | ${relPath} |`;
  });

  const index = [
    "# Document Index (Generated)",
    "",
    "> DO NOT hand-edit. Generated by `@aibos/docs-registry`.",
    "",
    "| Doc ID | Title | Version | Status | Authority | Checksum | Path |",
    "|--------|-------|--------:|--------|-----------|----------|------|",
    ...rows,
    "",
  ].join("\n");

  const indexPath = path.join(config.docsDir, "INDEX.md");
  fs.writeFileSync(indexPath, index, "utf8");
}
